# -*- makefile -*-
#----------------------------------------------------------------------------
#       GNU ACE Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/bin/mwc.pl -type gnuace
#
#----------------------------------------------------------------------------

MAKEFILE = GNUmakefile

ifeq ($(findstring k,$(MAKEFLAGS)),k)
  KEEP_GOING = -
endif

include $(ACE_ROOT)/include/makeinclude/macros.GNU

all: Tonnage_Idl Tonnage_Publisher Tonnage_Subscriber

depend: Tonnage_Idl-depend Tonnage_Publisher-depend Tonnage_Subscriber-depend

REMAINING_TARGETS := $(filter-out all depend,$(TARGETS_NESTED:.nested=)) $(CUSTOM_TARGETS)
.PHONY: $(REMAINING_TARGETS)

$(REMAINING_TARGETS):
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Tonnage_Idl $(@)
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Tonnage_Publisher $(@)
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Tonnage_Subscriber $(@)

.PHONY: Tonnage_Idl
Tonnage_Idl:
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Tonnage_Idl all

.PHONY: Tonnage_Idl-depend
Tonnage_Idl-depend:
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Tonnage_Idl depend

.PHONY: Tonnage_Publisher
Tonnage_Publisher: Tonnage_Idl
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Tonnage_Publisher all

.PHONY: Tonnage_Publisher-depend
Tonnage_Publisher-depend:
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Tonnage_Publisher depend

.PHONY: Tonnage_Subscriber
Tonnage_Subscriber: Tonnage_Idl Tonnage_Publisher
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Tonnage_Subscriber all

.PHONY: Tonnage_Subscriber-depend
Tonnage_Subscriber-depend:
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Tonnage_Subscriber depend

project_name_list:
	@echo Tonnage_Idl
	@echo Tonnage_Publisher
	@echo Tonnage_Subscriber
