// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.19
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:148

#ifndef _TAO_IDL_TONNAGETYPESUPPORTC_QFLBYA_H_
#define _TAO_IDL_TONNAGETYPESUPPORTC_QFLBYA_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types_IDLv4.h"
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "TonnageC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 5 || TAO_MICRO_VERSION != 19
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

namespace Mining
{

  
  // TAO_IDL - Generated from
  // /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

  

  typedef ::TAO::DCPS::ZeroCopyDataSeq< Mining::Tonnage, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> TonnageSeq;
  
  // TAO_IDL - Generated from
  // /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:747

  

#if !defined (_MINING_TONNAGETYPESUPPORT__VAR_OUT_CH_)
#define _MINING_TONNAGETYPESUPPORT__VAR_OUT_CH_

  class TonnageTypeSupport;
  typedef TonnageTypeSupport *TonnageTypeSupport_ptr;
  typedef TAO_Objref_Var_T<TonnageTypeSupport> TonnageTypeSupport_var;
  typedef TAO_Objref_Out_T<TonnageTypeSupport> TonnageTypeSupport_out;
  

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  TonnageTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:
    // TAO_IDL - Generated from
    // /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:301

    typedef TonnageTypeSupport_ptr _ptr_type;
    typedef TonnageTypeSupport_var _var_type;
    typedef TonnageTypeSupport_out _out_type;

    // The static operations.
    static TonnageTypeSupport_ptr _duplicate (TonnageTypeSupport_ptr obj);

    static void _tao_release (TonnageTypeSupport_ptr obj);

    static TonnageTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static TonnageTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static TonnageTypeSupport_ptr _nil (void);

    
    // TAO_IDL - Generated from
    // /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    TonnageTypeSupport (void);

    

    virtual ~TonnageTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (TonnageTypeSupport (const TonnageTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (TonnageTypeSupport (TonnageTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (TonnageTypeSupport &operator= (const TonnageTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (TonnageTypeSupport &operator= (TonnageTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
  };
  // TAO_IDL - Generated from
  // /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:747

  

#if !defined (_MINING_TONNAGEDATAWRITER__VAR_OUT_CH_)
#define _MINING_TONNAGEDATAWRITER__VAR_OUT_CH_

  class TonnageDataWriter;
  typedef TonnageDataWriter *TonnageDataWriter_ptr;
  typedef TAO_Objref_Var_T<TonnageDataWriter> TonnageDataWriter_var;
  typedef TAO_Objref_Out_T<TonnageDataWriter> TonnageDataWriter_out;
  

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  TonnageDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:
    // TAO_IDL - Generated from
    // /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:301

    typedef TonnageDataWriter_ptr _ptr_type;
    typedef TonnageDataWriter_var _var_type;
    typedef TonnageDataWriter_out _out_type;

    // The static operations.
    static TonnageDataWriter_ptr _duplicate (TonnageDataWriter_ptr obj);

    static void _tao_release (TonnageDataWriter_ptr obj);

    static TonnageDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static TonnageDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static TonnageDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::Mining::Tonnage & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::Mining::Tonnage & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::Mining::Tonnage & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::Mining::Tonnage & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::Mining::Tonnage & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::Mining::Tonnage & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::Mining::Tonnage & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::Mining::Tonnage & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Mining::Tonnage & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Mining::Tonnage & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    TonnageDataWriter (void);

    

    virtual ~TonnageDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (TonnageDataWriter (const TonnageDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (TonnageDataWriter (TonnageDataWriter &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (TonnageDataWriter &operator= (const TonnageDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (TonnageDataWriter &operator= (TonnageDataWriter &&))
#endif /* ACE_HAS_CPP11 */
  };
  // TAO_IDL - Generated from
  // /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:747

  

#if !defined (_MINING_TONNAGEDATAREADER__VAR_OUT_CH_)
#define _MINING_TONNAGEDATAREADER__VAR_OUT_CH_

  class TonnageDataReader;
  typedef TonnageDataReader *TonnageDataReader_ptr;
  typedef TAO_Objref_Var_T<TonnageDataReader> TonnageDataReader_var;
  typedef TAO_Objref_Out_T<TonnageDataReader> TonnageDataReader_out;
  

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  TonnageDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:
    // TAO_IDL - Generated from
    // /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:301

    typedef TonnageDataReader_ptr _ptr_type;
    typedef TonnageDataReader_var _var_type;
    typedef TonnageDataReader_out _out_type;

    // The static operations.
    static TonnageDataReader_ptr _duplicate (TonnageDataReader_ptr obj);

    static void _tao_release (TonnageDataReader_ptr obj);

    static TonnageDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static TonnageDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static TonnageDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::Mining::TonnageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::Mining::TonnageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::Mining::TonnageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::Mining::TonnageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::Mining::Tonnage & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::Mining::Tonnage & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::Mining::TonnageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::Mining::TonnageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::Mining::TonnageSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::Mining::TonnageSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::Mining::TonnageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::Mining::TonnageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::Mining::TonnageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::Mining::TonnageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::Mining::TonnageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Mining::Tonnage & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Mining::Tonnage & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    TonnageDataReader (void);

    

    virtual ~TonnageDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (TonnageDataReader (const TonnageDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (TonnageDataReader (TonnageDataReader &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (TonnageDataReader &operator= (const TonnageDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (TonnageDataReader &operator= (TonnageDataReader &&))
#endif /* ACE_HAS_CPP11 */
  };


// TAO_IDL - Generated from
// /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62


} // module Mining
// TAO_IDL - Generated from
// /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_MINING_TONNAGETYPESUPPORT__TRAITS_)
#define _MINING_TONNAGETYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::Mining::TonnageTypeSupport>
  {
    static ::Mining::TonnageTypeSupport_ptr duplicate (
        ::Mining::TonnageTypeSupport_ptr p);
    static void release (
        ::Mining::TonnageTypeSupport_ptr p);
    static ::Mining::TonnageTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Mining::TonnageTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_MINING_TONNAGEDATAWRITER__TRAITS_)
#define _MINING_TONNAGEDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::Mining::TonnageDataWriter>
  {
    static ::Mining::TonnageDataWriter_ptr duplicate (
        ::Mining::TonnageDataWriter_ptr p);
    static void release (
        ::Mining::TonnageDataWriter_ptr p);
    static ::Mining::TonnageDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Mining::TonnageDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_MINING_TONNAGEDATAREADER__TRAITS_)
#define _MINING_TONNAGEDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::Mining::TonnageDataReader>
  {
    static ::Mining::TonnageDataReader_ptr duplicate (
        ::Mining::TonnageDataReader_ptr p);
    static void release (
        ::Mining::TonnageDataReader_ptr p);
    static ::Mining::TonnageDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Mining::TonnageDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1649

#if defined (__ACE_INLINE__)
#include "TonnageTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

