// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.19
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:454

#ifndef _TAO_IDL_TONNAGES_8YKVHM_H_
#define _TAO_IDL_TONNAGES_8YKVHM_H_

#include /**/ "ace/pre.h"

#include "TonnageC.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

// TAO_IDL - Generated from
// /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::Mining::Tonnage>
    : public
        Fixed_Size_SArg_Traits_T<
            ::Mining::Tonnage,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:34

namespace POA_Mining
{
  


// TAO_IDL - Generated from
// /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_sh.cpp:65

} // module Mining

#include /**/ "ace/post.h"

#endif /* ifndef */

