// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.19
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "TonnageTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "TonnageTypeSupportC.inl"
#endif /* !defined INLINE */
// TAO_IDL - Generated from
// /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Mining::TonnageTypeSupport.

Mining::TonnageTypeSupport_ptr
TAO::Objref_Traits<Mining::TonnageTypeSupport>::duplicate (
    Mining::TonnageTypeSupport_ptr p)
{
  return Mining::TonnageTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<Mining::TonnageTypeSupport>::release (
    Mining::TonnageTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

Mining::TonnageTypeSupport_ptr
TAO::Objref_Traits<Mining::TonnageTypeSupport>::nil (void)
{
  return Mining::TonnageTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Mining::TonnageTypeSupport>::marshal (
    const Mining::TonnageTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Mining::TonnageTypeSupport::TonnageTypeSupport (void)
{}

Mining::TonnageTypeSupport::~TonnageTypeSupport (void)
{
}

Mining::TonnageTypeSupport_ptr
Mining::TonnageTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return TonnageTypeSupport::_duplicate (
      dynamic_cast<TonnageTypeSupport_ptr> (_tao_objref));
}

Mining::TonnageTypeSupport_ptr
Mining::TonnageTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return TonnageTypeSupport::_duplicate (
      dynamic_cast<TonnageTypeSupport_ptr> (_tao_objref));
}

Mining::TonnageTypeSupport_ptr
Mining::TonnageTypeSupport::_nil (void)
{
  return 0;
}

Mining::TonnageTypeSupport_ptr
Mining::TonnageTypeSupport::_duplicate (TonnageTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Mining::TonnageTypeSupport::_tao_release (TonnageTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Mining::TonnageTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Mining/TonnageTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Mining::TonnageTypeSupport::_interface_repository_id (void) const
{
  return "IDL:Mining/TonnageTypeSupport:1.0";
}

::CORBA::Boolean
Mining::TonnageTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Mining::TonnageDataWriter.

Mining::TonnageDataWriter_ptr
TAO::Objref_Traits<Mining::TonnageDataWriter>::duplicate (
    Mining::TonnageDataWriter_ptr p)
{
  return Mining::TonnageDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<Mining::TonnageDataWriter>::release (
    Mining::TonnageDataWriter_ptr p)
{
  ::CORBA::release (p);
}

Mining::TonnageDataWriter_ptr
TAO::Objref_Traits<Mining::TonnageDataWriter>::nil (void)
{
  return Mining::TonnageDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Mining::TonnageDataWriter>::marshal (
    const Mining::TonnageDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Mining::TonnageDataWriter::TonnageDataWriter (void)
{}

Mining::TonnageDataWriter::~TonnageDataWriter (void)
{
}

Mining::TonnageDataWriter_ptr
Mining::TonnageDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return TonnageDataWriter::_duplicate (
      dynamic_cast<TonnageDataWriter_ptr> (_tao_objref));
}

Mining::TonnageDataWriter_ptr
Mining::TonnageDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return TonnageDataWriter::_duplicate (
      dynamic_cast<TonnageDataWriter_ptr> (_tao_objref));
}

Mining::TonnageDataWriter_ptr
Mining::TonnageDataWriter::_nil (void)
{
  return 0;
}

Mining::TonnageDataWriter_ptr
Mining::TonnageDataWriter::_duplicate (TonnageDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Mining::TonnageDataWriter::_tao_release (TonnageDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Mining::TonnageDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Mining/TonnageDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Mining::TonnageDataWriter::_interface_repository_id (void) const
{
  return "IDL:Mining/TonnageDataWriter:1.0";
}

::CORBA::Boolean
Mining::TonnageDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /home/tarun/dds/OpenDDS-3.24.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Mining::TonnageDataReader.

Mining::TonnageDataReader_ptr
TAO::Objref_Traits<Mining::TonnageDataReader>::duplicate (
    Mining::TonnageDataReader_ptr p)
{
  return Mining::TonnageDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<Mining::TonnageDataReader>::release (
    Mining::TonnageDataReader_ptr p)
{
  ::CORBA::release (p);
}

Mining::TonnageDataReader_ptr
TAO::Objref_Traits<Mining::TonnageDataReader>::nil (void)
{
  return Mining::TonnageDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Mining::TonnageDataReader>::marshal (
    const Mining::TonnageDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Mining::TonnageDataReader::TonnageDataReader (void)
{}

Mining::TonnageDataReader::~TonnageDataReader (void)
{
}

Mining::TonnageDataReader_ptr
Mining::TonnageDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return TonnageDataReader::_duplicate (
      dynamic_cast<TonnageDataReader_ptr> (_tao_objref));
}

Mining::TonnageDataReader_ptr
Mining::TonnageDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return TonnageDataReader::_duplicate (
      dynamic_cast<TonnageDataReader_ptr> (_tao_objref));
}

Mining::TonnageDataReader_ptr
Mining::TonnageDataReader::_nil (void)
{
  return 0;
}

Mining::TonnageDataReader_ptr
Mining::TonnageDataReader::_duplicate (TonnageDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Mining::TonnageDataReader::_tao_release (TonnageDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Mining::TonnageDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Mining/TonnageDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Mining::TonnageDataReader::_interface_repository_id (void) const
{
  return "IDL:Mining/TonnageDataReader:1.0";
}

::CORBA::Boolean
Mining::TonnageDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

