/* -*- C++ -*- */
/* Generated by /home/tarun/dds/OpenDDS-3.24.1/bin/opendds_idl version 3.24.1 (ACE version 6.5.19) running on input file Tonnage.idl */
#ifndef OPENDDS_IDL_GENERATED_TONNAGETYPESUPPORTIMPL_H_O3NXIK
#define OPENDDS_IDL_GENERATED_TONNAGETYPESUPPORTIMPL_H_O3NXIK

#include <dds/Version.h>
#if !OPENDDS_VERSION_EXACTLY(3, 24, 1)
#  error "This file should be regenerated with opendds_idl"
#endif
#include <dds/DCPS/Definitions.h>

#include <dds/DdsDcpsC.h>

#include "TonnageC.h"
#include "TonnageTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/TypeSupportImpl.h"
#include "dds/DCPS/Util.h"
#include "dds/DCPS/ValueDispatcher.h"
#include "dds/DCPS/ValueReader.h"
#include "dds/DCPS/ValueWriter.h"
#include "dds/DCPS/XTypes/DynamicDataAdapter.h"
#include "dds/DCPS/XTypes/TypeObject.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: Mining */



/* Begin STRUCT: Tonnage */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct Mining_Tonnage_xtag {};
template<> const XTypes::TypeIdentifier& getMinimalTypeIdentifier<Mining_Tonnage_xtag>();

template<> const XTypes::TypeMap& getMinimalTypeMap<Mining_Tonnage_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vread(OpenDDS::DCPS::ValueReader& value_reader,  ::Mining::Tonnage& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const  ::Mining::Tonnage& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<> void set_default( ::Mining::Tonnage& stru);

void serialized_size(const Encoding& encoding, size_t& size, const ::Mining::Tonnage& stru);

bool operator<<(Serializer& strm, const ::Mining::Tonnage& stru);

bool operator>>(Serializer& strm,  ::Mining::Tonnage& stru);

void serialized_size(const Encoding& encoding, size_t& size, const NestedKeyOnly<const ::Mining::Tonnage>& stru);

bool operator<<(Serializer& strm, const NestedKeyOnly<const ::Mining::Tonnage>& stru);

bool operator>>(Serializer& strm, const NestedKeyOnly< ::Mining::Tonnage>& stru);

void serialized_size(const Encoding& encoding, size_t& size, const KeyOnly<const ::Mining::Tonnage>& stru);

bool operator<<(Serializer& strm, const KeyOnly<const ::Mining::Tonnage>& stru);

bool operator>>(Serializer& strm, const KeyOnly< ::Mining::Tonnage>& stru);

template <>
struct MarshalTraits< ::Mining::Tonnage> {
  static void representations_allowed_by_type(DDS::DataRepresentationIdSeq& seq)
  {
    seq.length(4);
    seq[0] = DDS::XCDR_DATA_REPRESENTATION;
    seq[1] = DDS::XCDR2_DATA_REPRESENTATION;
    seq[2] = DDS::XML_DATA_REPRESENTATION;
    seq[3] = OpenDDS::DCPS::UNALIGNED_CDR_DATA_REPRESENTATION;
  }

  static SerializedSizeBound serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound(20);
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static SerializedSizeBound key_only_serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound(0);
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static bool to_message_block(ACE_Message_Block&, const  ::Mining::Tonnage&) { return false; }
  static bool from_message_block( ::Mining::Tonnage&, const ACE_Message_Block&) { return false; }
  static Extensibility extensibility() { return APPENDABLE; }
  static Extensibility max_extensibility_level() { return APPENDABLE; }
};
} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace Mining {
/// This structure supports use of std::map with one or more keys.
struct  Tonnage_OpenDDS_KeyLessThan {
  bool operator()(const  ::Mining::Tonnage&, const  ::Mining::Tonnage&) const
  {
    // With no keys, return false to allow use of
    // map with just one entry
    return false;
  }
};
}


namespace Mining {
class TonnageTypeSupportImpl;
}

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS {
namespace DCPS {
template <>
struct DDSTraits< ::Mining::Tonnage> {
  typedef  ::Mining::Tonnage MessageType;
  typedef  ::Mining::TonnageSeq MessageSequenceType;
  typedef  ::Mining::TonnageSeq::PrivateMemberAccess MessageSequenceAdapterType;
  typedef  ::Mining::TonnageTypeSupport TypeSupportType;
  typedef  ::Mining::TonnageTypeSupportImpl TypeSupportImplType;
  typedef  ::Mining::TonnageDataWriter DataWriterType;
  typedef  ::Mining::TonnageDataReader DataReaderType;
  typedef  ::Mining::Tonnage_OpenDDS_KeyLessThan LessThanType;
  typedef OpenDDS::DCPS::KeyOnly<const  ::Mining::Tonnage> KeyOnlyType;
  typedef OpenDDS::DCPS::Mining_Tonnage_xtag XtagType;

  static const char* type_name() { return "Mining::Tonnage"; }
  static size_t key_count() { return 0; }
  static bool is_key(const char*);
};
} // namespace DCPS
} // namespace OpenDDS
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace Mining {
class  TonnageTypeSupportImpl
  : public virtual OpenDDS::DCPS::LocalObject<TonnageTypeSupport>
  , public virtual OpenDDS::DCPS::TypeSupportImpl_T<Tonnage>
  , public virtual OpenDDS::DCPS::ValueDispatcher_T<Tonnage>
{
public:
  typedef TonnageTypeSupport TypeSupportType;
  typedef TonnageTypeSupport::_var_type _var_type;
  typedef TonnageTypeSupport::_ptr_type _ptr_type;

  TonnageTypeSupportImpl() {}
  virtual ~TonnageTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType() const;
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */

  virtual const OpenDDS::XTypes::TypeIdentifier& getMinimalTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getMinimalTypeMap() const;

  virtual const OpenDDS::XTypes::TypeIdentifier& getCompleteTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getCompleteTypeMap() const;

  static TonnageTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};

}

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct< ::Mining::Tonnage>();
bool gen_skip_over(Serializer& ser,  ::Mining::Tonnage*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Mining::Tonnage,  ::Mining::Tonnage>(DDS::DynamicType_ptr type, const  ::Mining::Tonnage& value);

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Mining::Tonnage,  ::Mining::Tonnage>(DDS::DynamicType_ptr type,  ::Mining::Tonnage& value);

template <>
const  ::Mining::Tonnage* get_dynamic_data_adapter_value< ::Mining::Tonnage,  ::Mining::Tonnage>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End STRUCT: Tonnage */

/* End MODULE: Mining */
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif /* OPENDDS_IDL_GENERATED_TONNAGETYPESUPPORTIMPL_H_O3NXIK */
